CREATE DATABASE employees_db;

USE employees_db;

CREATE TABLE departments(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE roles(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  title VARCHAR(30) UNIQUE NOT NULL,
  salary DECIMAL UNSIGNED NOT NULL,
  departmentId INT UNSIGNED NOT NULL,
  FOREIGN KEY(departmentId) REFERENCES departments(id)
);

CREATE TABLE employees(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  firstName VARCHAR(30) NOT NULL,
  lastName VARCHAR(30) NOT NULL,
  roleId INT UNSIGNED NOT NULL,
  managerId INT UNSIGNED,
  FOREIGN KEY(roleId) REFERENCES roles(id),
  FOREIGN KEY(managerId) REFERENCES employees(id)
);